### ISSUE TITLE
Default font size

### ISSUE THREAD

**Issue by Akrzem** [eckinox/tinymce-bundle#5]
I use tinymce-bundle in Symfony 6 in form type - TinymceType::class

How to set default fontsize - font_size_formats

In doc where is:

tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  toolbar: 'fontsize',
  font_size_formats: '8pt 10pt 12pt 14pt 16pt 18pt 24pt 36pt 48pt'
});

**Comment by EmilePerron** [comment]
Hey @Akrzem,

I think this is what you're looking for:
https://www.tiny.cloud/docs/tinymce/6/webcomponent-ref/#setting-additional-configuration-options

A more detailed example of a similar issue was provided here: https://github.com/eckinox/tinymce-bundle/issues/4#issuecomment-1405032707

Hope that helps!
